import { Transaction, TransactionStatus } from './types';

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    transaction_id: 'TRX-2023-001-A',
    title: 'Executive Dinner - Client Meeting',
    amount_idr: 15000000,
    category: 'Entertainment',
    description: 'Dinner with potential clients at luxury restaurant. No attendee list attached.',
    date: '2023-10-25',
    status: TransactionStatus.PENDING,
    historical_average: 2000000,
    materiality_threshold: 10000000,
  },
  {
    id: '2',
    transaction_id: 'TRX-2023-002-B',
    title: 'Server Maintenance Hardware',
    amount_idr: 45000000,
    category: 'IT Infrastructure',
    description: 'Procurement of replacement hard drives for data center.',
    date: '2023-10-26',
    status: TransactionStatus.PENDING,
    historical_average: 50000000,
    materiality_threshold: 100000000,
  },
  {
    id: '3',
    transaction_id: 'TRX-2023-003-C',
    title: 'Consultation Fee - Unknown Vendor',
    amount_idr: 85000000,
    category: 'Consulting',
    description: 'Urgent consultation fee for regulatory compliance assistance. Vendor not in master data.',
    date: '2023-10-27',
    status: TransactionStatus.PENDING,
    historical_average: 15000000,
    materiality_threshold: 50000000,
  },
  {
    id: '4',
    transaction_id: 'TRX-2023-004-D',
    title: 'Office Supplies Q4',
    amount_idr: 2500000,
    category: 'Operational',
    description: 'Restocking paper, ink, and stationery for HQ.',
    date: '2023-10-28',
    status: TransactionStatus.APPROVED,
    historical_average: 3000000,
    materiality_threshold: 5000000,
  },
   {
    id: '5',
    transaction_id: 'TRX-2023-005-E',
    title: 'Marketing Agency Retainer',
    amount_idr: 120000000,
    category: 'Marketing',
    description: 'Monthly retainer for digital advertising services as per contract #MKT-2023.',
    date: '2023-10-29',
    status: TransactionStatus.PENDING,
    historical_average: 120000000,
    materiality_threshold: 150000000,
  },
];

export const APP_NAME = "AuditGuard AI";
